### ISSUE TITLE
Jumping scrolling noticeable near footer

### ISSUE THREAD

**Issue by samblackk** [planetary/crappyhour#25]
Check this screen recording for example: http://cl.ly/0w111Z0h181i

**Comment by ilikescience** [comment]
This becomes especially noticeable now that the body div is a bit bigger. This scrolling behavior makes my head hurt 😵 

on master: http://cl.ly/2E3F2o1Y060C
on development: http://cl.ly/1J3n1G0n3n1v

**Comment by ilikescience** [comment]
Closed by #32
