### ISSUE TITLE
100vh on chrome mobile

### ISSUE THREAD

**Issue by samblackk** [planetary/crappyhour#28]
"There is a problem when using 100vh on chrome mobile.
As it doesn’t take into consideration the address bar."

**Comment by ilikescience** [comment]
@singram26 was this addressed by your #32?

**Comment by samblackk** [comment]
@ilikescience no, this is separate.

**Comment by ilikescience** [comment]
Not quite sure I understand what the bug looks like — @Sidlav could you provide a screenshot or additional context?

**Comment by ilikescience** [comment]
Wasn't an issue after all!
