### ISSUE TITLE
Keep content within colored area on browser widths between 768px and 960px

### ISSUE THREAD

**Issue by vincejoyiv** [planetary/crappyhour#42]
Right now, the text, logo, and submit button are spilling out of the frame when the window is < 960px wide and > 768px. 

![screen shot 2016-07-08 at 5 32 17 pm](https://cloud.githubusercontent.com/assets/13005624/16702426/cbb5d08e-4533-11e6-9308-ffe1a60c78c1.png)

This is also causing a weird jump to happen when the content is scrolled.

![crappyhourbug](https://cloud.githubusercontent.com/assets/13005624/16702681/a891bc2e-4535-11e6-9a78-a989ec180792.gif)

**Comment by ilikescience** [comment]
Closed by #44
