### ISSUE TITLE
Update clock and button styles

### ISSUE THREAD

**Issue by vincejoyiv** [planetary/crappyhour#43]
To make the clocks more legible give the clock faces no stroke, and a fill of `rgba(0, 0, 0, 0.1)`.
![screen shot 2016-07-12 at 10 55 24 am](https://cloud.githubusercontent.com/assets/13005624/16771618/2b644b4e-481f-11e6-8797-77e16c00601e.png)
To make the button match the clock styling, give it a fill of `rgba(0, 0, 0, 0.1)` and a bottom border of 2px #000000.
![screen shot 2016-07-12 at 10 57 00 am](https://cloud.githubusercontent.com/assets/13005624/16771688/639b9e54-481f-11e6-930d-903777c3c49a.png)
This gives us the added benefit of only having one element that is `#c0ffee` colored.

**Comment by ilikescience** [comment]
Closed by #45
